name: Deploy Infrastructure

on:
  workflow_dispatch:
    # or on: push

permissions:
  contents: read
  id-token: write

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform -chdir=iac init

      - name: Terraform Plan
        run: terraform -chdir=iac plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=iac apply -auto-approve tfplan
