name: Deploy Infrastructure

on:
  workflow_dispatch: {}

permissions:
  contents: read   # No id-token: write needed

jobs:
  deploy_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform -chdir=iac init

      - name: Terraform Plan
        run: terraform -chdir=iac plan -out=tfplan

      - name: Terraform Apply
        run: terraform -chdir=iac apply -auto-approve tfplan
